# Generated by Django 4.0.3 on 2023-05-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_comment_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_count',
            field=models.IntegerField(default=0),
        ),
    ]
